In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)  #Casting list into array.

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,3))  #Tuple is given as input to make two dimensional arrays

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.linspace(0,10,5)   # Returns equally spaced points between range

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
np.eye(4) # Returns identity matrix.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(5) # Uniform distribution.

array([0.50204851, 0.96301989, 0.78246537, 0.04865517, 0.90975756])

In [15]:
np.random.randn(4,4) # Normal distribution.

array([[-0.92607992, -0.28206677, -0.89766167,  1.32184905],
       [-0.26333159,  0.30497186,  0.0734049 , -0.08497549],
       [-0.4426726 ,  0.03420327, -0.81850529, -1.5108854 ],
       [-0.36567102,  0.93148058,  0.09525842,  0.58517447]])

In [16]:
np.random.randint(1,100,10) # 10 random ints from [1,100). 

array([92, 70, 90, 30, 17, 26, 81, 64, 85, 43])

In [17]:
arr1 = np.arange(0,25)

In [18]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
arr1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
arr1.max()

24

In [21]:
arr1.min()

0

In [22]:
ranarr = np.random.randint(1,100,10)

In [23]:
ranarr

array([60, 34, 91, 14, 85, 62, 52, 49, 18, 65])

In [24]:
ranarr.argmax() # index of max value.

2

In [25]:
ranarr.argmin() # index of min value.

3

In [26]:
arr1.shape

(25,)

In [27]:
arr1 = arr1.reshape(5,5)

In [28]:
arr1.shape

(5, 5)

In [29]:
arr1.dtype

dtype('int32')

In [30]:
# NumPy indexing and selection.

In [31]:
array1 = np.arange(0,11)

In [32]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
array1[2:5]

array([2, 3, 4])

In [34]:
array1[5:]

array([ 5,  6,  7,  8,  9, 10])

In [35]:
array1[5:8] = 100

In [36]:
array1

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9,  10])

In [37]:
array1 = np.arange(0,11)

In [38]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
slice_of_array1 = array1[0:6]

In [40]:
slice_of_array1

array([0, 1, 2, 3, 4, 5])

In [41]:
slice_of_array1 [:] = 7

In [42]:
slice_of_array1

array([7, 7, 7, 7, 7, 7])

In [43]:
array1_copy = array1.copy()

In [44]:
array1_copy

array([ 7,  7,  7,  7,  7,  7,  6,  7,  8,  9, 10])

In [45]:
array1_copy[6:] = 2

In [46]:
array1_copy

array([7, 7, 7, 7, 7, 7, 2, 2, 2, 2, 2])

In [47]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [48]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [49]:
arr_2d[1][2]

30

In [50]:
arr_2d[1,2]

30

In [51]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [52]:
arr2 = np.arange(1,11)

In [53]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr2 > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [55]:
arr2_bool = arr2 > 5

In [56]:
arr2_bool

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [57]:
arr2[arr2_bool]

array([ 6,  7,  8,  9, 10])

In [58]:
arr2[arr2>5]

array([ 6,  7,  8,  9, 10])

In [59]:
arr2d = np.arange(50).reshape(5,10)

In [60]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [61]:
arr2d[1:3,3:5]

array([[13, 14],
       [23, 24]])